ci:
  skip: [pytest]

default_language_version:
  python: python3

repos:

  - repo: local
    hooks:
      # Ruff linting
      - id: ruff
        name: ruff
        entry: uv run ruff check .
        language: python
        types: [python]

      # Ruff formatting
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format .
        language: python
        types: [python]

      # Mypy type checking
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]

      # Docformatter
      - id: docformatter
        name: docformatter
        entry: uv run docformatter -r -i --pre-summary-newline --make-summary-multi-line --wrap-summaries 90 --wrap-descriptions 90 src tests
        language: python
        types: [python]
        additional_dependencies: [docformatter]

      # Bandit security checks
      - id: bandit
        name: bandit
        entry: uv run bandit -r src
        language: system
        types: [python]
        exclude: ^tests/

      # Pytest
      - id: pytest
        name: pytest
        entry: uv run pytest tests --cov=src
        language: python
        types: [python]
        pass_filenames: false
